### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by zeinalii** [data301-2020-winter2/course-project-group_1025#2]
## High priority (must-fix)

- [x] add a structure to your report. It is better to have an introduction that gives the reader some information about the data and your question. 

- [x] Combine all tasks into one single file.

- [x] Your visualization for RQ1 is hard to interpret. Maybe try some other methods of visualization. Maybe Scatter plot with a fitted line?
- [x] RQ2 visualization is confusing. Maybe try using violin plot.

- [x] Printing the dataset alone does not explain the data. You need to add a section called dataset and explain the data. What are the columns and what do they show?
- [x] Can you plot a map for Q3? based on longitudeand latitude data? X-axis in your plot is confusing.
- [x] Q4 plot is very messy and hard to interpret.  Maybe try using box plot for this question. x axis the room type and y-axis price.

- [x] Some of the plots do not have proper labels. For example, what is the unit of price?

## Low priority (fix if there is time)

- [x] Make your report look better by using markdown tools such as the followings: 
                    Multi-level Headers (``, ##, ###, #### etc…)
                    Bold text (surround with **bold text**)
                    Italic text (surround with *italic text*)
                    Unordered lists (- text or * text, + text)
                    Ordered lists (1. text)
                    Images (![path_to_image.png])
                    Code (surround code in markdown cells with single line or multi-line code)
                    Quoted text (start line with > text)
                    Links ([text placeholder](https:/cbc.ca))
                    Math symbols using $\latex(surroundwith‘‘like:‘$\lambda`)
                    Horizontal Line (three dashes: ---)

**Comment by SanjanaCode** [comment]
Closed all the issues: Sanjana
